services:
  varnish:
    container_name: varnish
    build: ./varnish
    ports:
      - 8080:8080
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    volumes:
      - ./config:/config
      - ./storage:/storage

  tinyproxy:
    container_name: tinyproxy
    build: ./tinyproxy
    ports:
      - 8888:8888
    command: tinyproxy -c /etc/tinyproxy/tinyproxy.conf -d
    volumes:
      - ./config/tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf:ro

  hitch:
    container_name: hitch
    image: "hitch:1"
    ports:
      - 8443:8443
    volumes:
      - ./config/hitch.conf:/etc/hitch/hitch.conf:ro
